### ISSUE TITLE
"File could not be opened" with MMX4 save

### ISSUE THREAD

**Issue by malvarenga123** [ShendoXT/memcardrex#24] opened 2021-09-18 16:11 UTC
Hi, I recently copied all my PS1 saves from memory cards using wlaunchelf on my PS2. To make them more useable, I created .mcr files with memcardrex and started importing the saves. All my saves worked except the one attached, which shows the error:
"File could not be opened"
Did that save become corrupted?
[BASLUS-00561.zip](https://github.com/ShendoXT/memcardrex/files/7190233/BASLUS-00561.zip)

**Comment by malvarenga123** [comment] 2021-09-18 19:48
An update:
I downloaded the first gme file from [here](https://gamefaqs.gamespot.com/ps/197898-mega-man-x4/saves) and memcardrex is able to open and export the MMX4 save as a raw single save file, but it cannot import the file it just exported.

**Comment by ndepoel** [comment] 2021-09-19 11:44
I had a look at your save file and how MemcardRex handles it. Turns out the save's header is slightly misformatted; instead of the file starting with the letters "SC" it starts with the lowercase "sc" instead. I manually edited the save file with a hex editor and now it loads just fine in MemcardRex. I'm not sure if this should be considered as an issue in MemcardRex (it could easily be modified to accept lowercase save headers) or if it's an issue caused by the save export process.

Either way I've attached the fixed save file so you can continue using it:
[BASLUS-00561-fixed.zip](https://github.com/ShendoXT/memcardrex/files/7192012/BASLUS-00561-fixed.zip)

**Comment by malvarenga123** [comment] 2021-09-19 18:04
> if it's an issue caused by the save export process.
I don't think it's a issue with the export process, because both wlaunchelf and memcardrex exported the save with lowercase SC. Out of a few dozen saves, this was the only one that had this issue.

**Comment by ShendoXT** [comment] 2021-09-22 02:53
Well if that's how the save is legitimately created and valid in the eyes of the real PS1 then this edge case should be supported

**Comment by malvarenga123** [comment] 2021-09-22 03:20
I'm not sure how the save inside a gme file is handled, but memcardrex was able to read it just fine, and even export it.

**Comment by ShendoXT** [comment] 2021-09-23 02:31
This should be fixed now, please check out the latest release.

**Closed by ShendoXT** 2021-09-23 02:31 UTC
