### ISSUE TITLE
When exporting RAW single save, everything in the destination path after and including "." is ignored

### ISSUE THREAD

**Issue by yousie642** [ShendoXT/memcardrex#36] opened 2022-11-08 15:10 UTC
This can be reproduced by exporting to a path like `C:\Users\[username]\Downloads\MemcardRex.1.9.cd98032\BASLUS-006640` with `BASLUS-006640` being the file name of the RAW single save.
You will instead wind up with a RAW single save called `MemcardRex` under `C:\Users\[username]\Downloads`

This is also seen when exporting a RAW single save where the save file identifier includes a `.` like in Tales of Phantasia
![image](https://user-images.githubusercontent.com/43191177/200598597-b6643bed-f3a7-4626-ba43-b6b7b6a50361.png)
Exporting this save as a RAW single save attempts to name the file as `BISLPSP01770.TOP.C` (on 1.9.2b7a018 at least. There's a different issue on 1.9.cd98032 when you go to export where it replaces the identifier with a seemingly random string of characters). Instead, you wind up with a file called `BISLPSP01770`

**Comment by ShendoXT** [comment] 2022-12-18 01:37
Oh snap, you are absolutely right. I even know what the issue is... Save file dialog leaves extensions when selecting file type even when raw save is selected.
So my solution was to trim everything after the dot since it "must" be an extension which save file dialog did not clear...

I'll just have to remove this piece of code and rely on user to trim the extension if the stupid save dialog leaves it...

**Comment by ShendoXT** [comment] 2022-12-18 02:05
Fixed as of [75fb97c](https://github.com/ShendoXT/memcardrex/commit/75fb97c21faae227f8fdd17a8e319c26ce214515)

**Closed by ShendoXT** 2022-12-18 02:05 UTC
